### ekf config file ###
ekf_filter_node:
    ros__parameters:
        use_sim_time: true       
        frequency: 50.0
        two_d_mode: true
        transform_time_offset: 0.0
        transform_timeout: 0.0
        publish_tf: true
        publish_acceleration: false
        reset_on_time_jump: true

        odom_frame: odom                 # Defaults to "odom" if unspecified
        base_link_frame: base_footprint  # Defaults to "base_link" if unspecified
        world_frame: odom                # Defaults to the value of odom_frame if unspecified


        odom0: diff_drive_controller/odom
        odom0_config: [true, true, false,
                       false, false, true,
                       true,  true,  true,
                      false, false, false,
                       false, false, false]

        #odom0_queue_size: 2
        #odom0_nodelay: false
        #odom0_differential: false
        #odom0_relative: false
        #odom0_pose_rejection_threshold: 5.0
        #odom0_twist_rejection_threshold: 1.0

        imu0: imu
        imu0_config: [false, false, false,
                      false,  false,  true,
                      false, false, false,
                      false,  false,  true,
                      false,  false,  false]

        #imu0_nodelay: false
        #imu0_differential: true
        #imu0_relative: true
        #imu0_queue_size: 7
        #imu0_pose_rejection_threshold: 0.8                
        #imu0_twist_rejection_threshold: 0.01              
        #imu0_linear_acceleration_rejection_threshold: 0.8  

        odom0: laser_odom
        odom0_config: [true, true, false,
                        false, false, true,
                        false, false, false,
                        false, false, false,
                        false, false, false]

        #laser0_queue_size: 5
        #laser0_nodelay: false

        